Repository Nouster/mspr-1-etl, pull requests merged in 2025-06, with the labels that each got.

#59 update ignore file
  .dockerignore
  .gitignore
Labels: bug

#61 prepare deploy front
  front/fly.toml
Labels: enhancement

#64 test pa11y
  .devcontainer/devcontainer.json
  .github/workflows/main.yml
Labels: documentation, enhancement

#66 no sandbox for pa11
  .github/workflows/main.yml
Labels: bug

#68 ignore file .toml
  .dockerignore
  .gitignore
Labels: bug
